#######################################################################################################################################################################
# seqtk
#######################################################################################################################################################################

FROM condaforge/mambaforge
LABEL maintainer="sagnikbanerjee15@gmail.com" 
LABEL org.opencontainers.image.source https://github.com/sagnikbanerjee15/dockerized_tools_and_pipelines

RUN mamba install -y -c bioconda seqtk=1.3
