#######################################################################################################################################################################
# ZPAQ
#######################################################################################################################################################################

FROM condaforge/mambaforge
LABEL maintainer="sagnikbanerjee15@gmail.com"

ENV TZ=America/New_York
ENV DEBIAN_FRONTEND=noninteractive

#RUN apt-get update
#RUN apt-get install -y time

RUN mamba install -c sbu-hpc -y zpaq=7.15